[project]
name = "saddogs-scrape"
version = "0.1.0"
description = ""
authors = [
    {name = "Jose Caballero",email = "jose.caballero@epicgames.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scrapy (>=2.14.1,<3.0.0)",
]

[tool.poetry]
packages = [{include = "saddogs-scrape"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
